### ISSUE TITLE
Wrong license for scopatz' stuff

### ISSUE THREAD

**Issue by mar77i** [serialhex/nano-highlight#24]
I just noticed this because it prevents me from copying from scopatz's repository. [0] doesn't look like WTFPL to me, but rather GPL3, which has a clause that you must republish under a compatible license.
That said, the licensing of your repository is unspecified.

[0] https://github.com/scopatz/nanorc/blob/master/license

**Comment by serialhex** [comment]
He may have changed it since then. When I initially built my package it was under the WTFPL, and looking at the repo, it seems like it was re-built from the ground up ~6 months ago.

I'll put a license file in the repo, to make it more explicit.  I want this to be as public as possible, so I was gonna make it MIT (unless otherwise specified), unless you have a better suggestion...

**Comment by mar77i** [comment]
I may point you to ISC which is said to be juridically equivalent but easier to understand.

**Comment by serialhex** [comment]
Sounds good, I'll use that one.

**Comment by serialhex** [comment]
I looked at that, but I think the unlicense for everything that's not really licensed works better, as most of it was public domain-ish anyway.  And I don't really care if people don't attribute me anyway, because most people don't (I mean, do you seriously expect your MIT/BSD/ISC stuff that other people use to have your name tagged onto it somewhere? I would hope so, but you're probably not going to sue someone if they didn't and you had the ability too)

Thanks for bringing this to my attention!  Take care!

**Comment by mar77i** [comment]
> I mean, do you seriously expect your MIT/BSD/ISC stuff that other people use to have your name tagged onto it somewhere?
Uh, I'm not necessarily able to look that up because MIT/BSD/ISC doesn't require users and redistributors to publish under an open source license themselves.
